name: Docker

on:
  workflow_call:

jobs:
  docker:
    strategy:
      matrix:
        include:
          - nginx_version: mainline
            nginx_package_src: "https://nginx.org/packages/mainline/debian/"
            latest: true
          - nginx_version: stable
            nginx_package_src: "https://nginx.org/packages/debian/"
            latest: false
    uses: "tweedegolf/actions-container-helpers/.github/workflows/container-image.yml@main"
    with:
        push: ${{ github.ref == 'refs/heads/main' }}
        platforms: "linux/amd64,linux/arm64"
        build-args: |
          NGINX_PACKAGE_SRC=${{matrix.nginx_package_src}}
        tags: |
            ghcr.io/tweedegolf/nginx:${{matrix.nginx_version}}
            ${{ matrix.latest && 'ghcr.io/tweedegolf/nginx:latest' || '' }}
